"""Generate the item reference from Unity's wiki export and maintained player notes.

Run the Editor's Rivet Reach > Export wiki items and icons first when game data
changes. This script uses only the Python standard library; --check writes nothing.
"""
from collections import Counter, defaultdict
from html import escape
from pathlib import Path
import argparse
import hashlib
import json
import re

ROOT = Path(__file__).resolve().parents[1]
WIKI = ROOT / '.docs/wiki'
DATA = ROOT / '.docs/wiki-data'
MARKER = '<!-- Generated by Tools/generate_wiki_items.py; edit .docs/wiki-data/item-notes.json. -->'


def page(item_id):
    return 'Item-' + item_id.split(':', 1)[1].replace('_', '-') + '.md'


def load_catalog():
    catalog = json.loads((DATA / 'catalog.json').read_text())
    stale = [source['path'] for source in catalog['sources']
             if not (ROOT / source['path']).is_file() or
             hashlib.sha256((ROOT / source['path']).read_bytes()).hexdigest() != source['sha256']]
    if stale:
        raise ValueError('Unity wiki export is stale; export again: ' + ', '.join(stale[:8]))
    return catalog


class Reference:
    def __init__(self, catalog):
        self.catalog = catalog
        self.items = {i['definition']['stableId']: i for i in catalog['items']}
        self.notes = json.loads((DATA / 'item-notes.json').read_text())
        if set(self.notes) - set(self.items):
            raise ValueError('Notes reference unknown items')
        self.outputs = defaultdict(list)
        self.uses = defaultdict(list)
        self.stations = defaultdict(list)
        self.fuels = defaultdict(list)
        self.numbers = {}
        for recipe in catalog['recipes']:
            output = recipe['output']['item']
            self.outputs[output].append(recipe)
            self.numbers[recipe['id']] = len(self.outputs[output])
            for item_id in {i['item'] for i in recipe['ingredients'] if i['item']}:
                self.uses[item_id].append(recipe)
            if recipe['station']:
                self.stations[recipe['station']].append(recipe)
            for fuel in recipe['fuels']:
                self.fuels[fuel].append(recipe)

    def name(self, item_id):
        return self.items[item_id]['definition']['displayName']

    def link(self, item_id, label=None, anchor=''):
        return f'[{label or self.name(item_id)}]({page(item_id)}{anchor})'

    def icon(self, item_id, size=48, label=False, count=None, anchor=''):
        name = escape(self.name(item_id), quote=True)
        target = page(item_id) + anchor
        number = self.items[item_id]['definition']['runtimeId']
        text = f'<a href="{target}" title="{name}"><img src="icons/{number}.png" width="{size}" height="{size}" alt="{name}">'
        if label:
            text += f'<br>{name}'
        text += '</a>'
        if count is not None:
            text += f' ×{count}'
        return text

    def group(self, item_id):
        item = self.items[item_id]
        d = item['definition']
        if 'starter_' in item_id:
            return 'Legacy test equipment'
        if d['toolCapabilities'] or item_id == 'rivet:wrench':
            return 'Tools and weapons'
        if d['armorSlot']:
            return 'Armor'
        if item['crop'] or d['foodPoints'] or item_id.endswith((':farmland', ':sapling')):
            return 'Food and farming'
        if item['ore'] or item_id.endswith(':bedrock'):
            return 'Ore deposits and bedrock'
        if d['runtimeId'] >= 160:
            return 'Multiblock tanks and batteries'
        if 131 <= d['runtimeId'] <= 138 or d['runtimeId'] in (146, 147, 148, 149):
            return 'Connections and controls'
        if d['runtimeId'] in (23, 24, 25, 130) or 139 <= d['runtimeId'] <= 145:
            return 'Stations and machines'
        if item_id in ('rivet:bucket', 'rivet:water_bucket', 'rivet:torch'):
            return 'Light and buckets'
        if item['placeable']:
            return 'Building blocks'
        return 'Materials and components'

    def description(self, item_id):
        item = self.items[item_id]
        d = item['definition']
        notes = self.notes.get(item_id, {})
        if 'description' in notes:
            return notes['description']
        if item['help']:
            return item['help'].rstrip('.') + '.'
        if d['toolCapabilities']:
            purpose = {1: 'Chops wood faster and fells connected tree sections above the cut.',
                       2: 'Mines stone and ore when its tier meets the deposit’s requirement.',
                       4: 'A melee weapon. It can also cut leaves faster.',
                       8: 'Digs dirt, grass and farmland faster.',
                       16: 'Tills grass or dirt into farmland and cuts leaves faster.'}
            return purpose[d['toolCapabilities']] + ' Tools currently have no durability loss.'
        if d['armorSlot']:
            slot = ['', 'head', 'chest', 'legs', 'feet'][d['armorSlot']]
            return f'Equip in the {slot} armor slot to add {d["armorPoints"]} protection points. The equipped piece appears on your explorer and the inventory portrait. Armor reduces incoming damage and currently has no durability loss.'
        if item_id.endswith('_block'):
            return 'A placeable storage block. Pack nine units into one block, then unpack it when you need the material again.'
        if item_id.startswith('rivet:crushed_'):
            return 'Crushed ore from powered processing. Smelt each piece into one matching ingot; crushing doubles the ingot yield of a raw ore item.'
        if item_id.endswith('_ingot'):
            return 'Smelted metal used in crafting. Direct smelting makes one ingot per raw ore; crushing first makes two crushed pieces, each worth one ingot.'
        raise ValueError('Missing player description: ' + item_id)

    def acquisition(self, item_id):
        item = self.items[item_id]
        notes = self.notes.get(item_id, {})
        if notes.get('obtain'):
            return notes['obtain']
        if item['ore']:
            return f'Find this deposit in stone. Mine it with a **{item["requiredTier"].lower()} pickaxe or better**.'
        drops = [i['definition']['stableId'] for i in self.items.values()
                 if i['drop'] == item_id and i['definition']['stableId'] != item_id and not i['crop']]
        if drops:
            return 'Gather by mining ' + ', '.join(self.link(i) for i in drops) + '. Follow each block’s tool requirement.'
        if self.outputs[item_id]:
            return 'Make this item using the crafting or processing recipes below.'
        raise ValueError('Missing acquisition note: ' + item_id)

    def recipe(self, recipe):
        lines = [f'### Recipe {self.numbers[recipe["id"]]}', '']
        station = recipe['station']
        lines += ['**Station:** ' + (self.icon(station, 40, True) if station else '[Personal crafting](Crafting-Recipes.md#personal-crafting--22)') +
                  (f' · {recipe["grid"]}×{recipe["grid"]}' if recipe['grid'] else ''), '']
        if recipe['kind'] != 'Processing':
            if recipe['kind'] == 'Shaped':
                lines += ['**Shaped:** keep the arrangement below. The pattern can move within a compatible grid.' +
                          (' Horizontal mirroring is also accepted.' if recipe['mirror'] else ''), '']
            else:
                lines += ['**Shapeless:** slot positions do not matter. Keep each pictured ingredient stack and its quantity; the layout below is only an example.', '']
            grid = recipe['grid']
            cells = [None] * (grid * grid)
            for n, entry in enumerate(recipe['ingredients']):
                pos = (n // recipe['width']) * grid + n % recipe['width'] if recipe['kind'] == 'Shaped' else n
                if pos >= len(cells):
                    raise ValueError('Recipe exceeds its grid: ' + recipe['id'])
                cells[pos] = entry if entry['item'] else None
            lines.append('<table>')
            for y in range(grid):
                lines.append('<tr>')
                for entry in cells[y * grid:(y + 1) * grid]:
                    contents = self.icon(entry['item'], count=entry['count']) if entry else '&nbsp;'
                    lines.append(f'<td align="center" width="72" height="64">{contents}</td>')
                lines.append('</tr>')
            lines += ['</table>', '']
        else:
            seconds = recipe['ticks'] / self.catalog['ticksPerSecond']
            lines += [f'**Processing time:** {seconds:g} seconds per operation' +
                      (f' at **{recipe["watts"]} W**. Reduced power slows progress.' if recipe['watts'] else '.'), '']
        lines += ['**Output:** ' + self.icon(recipe['output']['item'], 56, True, recipe['output']['count']), '',
                  '| Ingredient | Total per operation |', '|---|---:|']
        totals = Counter()
        for entry in recipe['ingredients']:
            if entry['item']:
                totals[entry['item']] += entry['count']
        for item_id, count in totals.items():
            lines.append(f'| {self.icon(item_id, 32)} {self.link(item_id)} | {count} |')
        lines.append('')
        if recipe['fuels']:
            lines += ['**Fuel:** add furnace fuel separately; it is not a crafting ingredient. ' +
                      ' · '.join(self.icon(f, 32) + ' ' + self.link(f) for f in recipe['fuels']) + '.', '',
                      'Fuel burns down after ignition even if the input runs out. See the ' + self.link(station) + ' page for fuel durations.', '']
        return lines

    def recipe_links(self, recipes):
        lines = ['| Result | Station | Recipe |', '|---|---|---|']
        for recipe in recipes:
            item_id = recipe['output']['item']
            anchor = '#recipe-' + str(self.numbers[recipe['id']])
            station = self.link(recipe['station']) if recipe['station'] else 'Personal 2×2'
            lines.append(f'| {self.icon(item_id, 32, count=recipe["output"]["count"], anchor=anchor)} {self.link(item_id)} | {station} | {self.link(item_id, "View recipe", anchor)} |')
        return lines + ['']

    def item_page(self, item_id):
        item = self.items[item_id]
        d = item['definition']
        lines = [MARKER, '', '# ' + d['displayName'], '', '[All items](Items.md) · [Crafting guide](Crafting-Recipes.md) · [Home](Home.md)', '',
                 '[How to obtain](#how-to-obtain) · [Crafting and processing](#crafting-and-processing)' +
                 (' · [Uses](#used-to-make)' if self.uses[item_id] else '') +
                 (' · [Recipes made here](#recipes-made-here)' if self.stations[item_id] else ''), '',
                 self.icon(item_id, 96), '', self.description(item_id), '', '## At a glance', '',
                 '| Property | Value |', '|---|---|', f'| Stack size | {d["stackLimit"]} |']
        if d['toolCapabilities']:
            lines += [f'| Tool tier | {["None", "Wood", "Stone", "Copper", "Iron", "Diamond"][d["tier"]]} |',
                      f'| Effective mining speed | {d["miningSpeed"]:g}× on suitable blocks |',
                      f'| Melee damage | {d["attackDamage"]} |']
        if d['armorPoints']:
            lines += [f'| Armor protection | {d["armorPoints"]} points |']
        if d['foodPoints']:
            lines += [f'| Food restored | {d["foodPoints"]} points |']
        if item['watts']:
            lines += [f'| Power demand | {item["watts"]} W |']
        if item['waterMl']:
            lines += [f'| Internal fluid capacity | {item["waterMl"] / 1000:g} L |']
        if item['fuelTicks']:
            lines += [f'| Furnace fuel duration | {item["fuelTicks"] / self.catalog["ticksPerSecond"]:g} seconds |']
        if item['requiredTier'] != 'None':
            lines += [f'| Required mining tool | {item["requiredTier"]} pickaxe or better |']
        if item['placeable']:
            lines += ['| Placement | Place from the hotbar |']
        elif item['ore'] or item['crop'] or item_id in ('rivet:farmland', 'rivet:bedrock'):
            lines += ['| Placement | World block; cannot be placed directly as an inventory item |']
        lines += ['', '## How to obtain', '', self.acquisition(item_id), '']
        if item['ore']:
            lines += ['Mining yields ' + self.icon(item['drop'], 40, True, 1) + '.', '']
        if self.notes.get(item_id, {}).get('use'):
            lines += ['## Using it', '', self.notes[item_id]['use'], '']
        if self.outputs[item_id]:
            lines += ['## Crafting and processing', '']
            for recipe in self.outputs[item_id]:
                lines += self.recipe(recipe)
        else:
            lines += ['## Crafting and processing', '', 'There is no registered crafting or processing recipe for this item. Use the acquisition method above.', '']
        if self.uses[item_id]:
            lines += ['## Used to make', '', 'Follow a result to see its complete ingredients and recipe.', ''] + self.recipe_links(self.uses[item_id])
        if self.stations[item_id]:
            lines += ['## Recipes made here', '', 'The station is reusable; it is not consumed by these recipes.', ''] + self.recipe_links(self.stations[item_id])
        if self.fuels[item_id]:
            lines += ['## Furnace fuel', '', f'One item supplies **{item["fuelTicks"] / self.catalog["ticksPerSecond"]:g} seconds** of burning fuel. ' +
                      'Use it in a ' + self.link('rivet:furnace') + ' for smelting or cooking.', '']
        if item_id == 'rivet:furnace':
            lines += ['## Fuel durations', '', '| Fuel | Seconds per item |', '|---|---:|']
            for fuel, entry in self.items.items():
                if entry['fuelTicks']:
                    lines.append(f'| {self.icon(fuel, 32)} {self.link(fuel)} | {entry["fuelTicks"] / self.catalog["ticksPerSecond"]:g} |')
            lines += ['']
        return '\n'.join(lines)

    def index(self):
        groups = defaultdict(list)
        for item_id in self.items:
            groups[self.group(item_id)].append(item_id)
        order = ['Building blocks', 'Ore deposits and bedrock', 'Materials and components', 'Tools and weapons', 'Armor',
                 'Food and farming', 'Light and buckets', 'Stations and machines', 'Connections and controls',
                 'Multiblock tanks and batteries', 'Legacy test equipment']
        lines = [MARKER, '', '# Items', '', 'Click any icon or item name for what it does, how to obtain it, its recipes, and the things you can make with it.', '',
                 '[Crafting guide](Crafting-Recipes.md) · [Home](Home.md)', '',
                 'Includes all **127 registered items and world-block entries** in the current playable alpha. Ore blocks, crops, bedrock and legacy test equipment have pages even when they cannot be crafted or placed.', '',
                 ' · '.join(f'[{g}](#{g.lower().replace(" ", "-")})' for g in order), '']
        for group in order:
            lines += ['## ' + group, '']
            if group == 'Legacy test equipment':
                lines += ['Historical test items available in the Creative catalog. Ordinary expeditions start empty-handed; these tools have no active crafting recipes.', '']
            lines += ['| | | | |', '|:---:|:---:|:---:|:---:|']
            entries = sorted(groups[group], key=lambda i: self.name(i).lower())
            for start in range(0, len(entries), 4):
                cells = [self.icon(i, 56, True) for i in entries[start:start + 4]]
                lines += ['| ' + ' | '.join(cells + [''] * (4 - len(cells))) + ' |']
            lines += ['']
        return '\n'.join(lines).replace('**127 registered', f'**{len(self.items)} registered')

    def crafting(self):
        lines = [MARKER, '', '# Crafting recipes', '',
                 'Start with the [visual item index](Items.md), then click an item to see its purpose, how to obtain it, every recipe that makes it, and what uses it. Every item icon links to its own page.', '',
                 'This reference covers **91 grid recipes, 11 furnace recipes and 3 crusher recipes** in the current playable alpha. The recipe grids and icons come from the same catalog and artwork used by the inventory browser.', '',
                 '## First crafting steps', '',
                 '1. Gather ' + self.link('rivet:log') + ' from a tree with your hands.',
                 '2. Turn one log into four ' + self.link('rivet:planks') + ' in personal crafting.',
                 '3. Fill the personal 2×2 grid with planks to make a ' + self.link('rivet:workbench') + '.',
                 '4. Place the workbench and open it with **E or right-click**. Make ' + self.link('rivet:stick') + ' and a ' + self.link('rivet:wood_pickaxe') + '.',
                 '5. Mine stone for ' + self.link('rivet:cobblestone') + ', then make better tools and a ' + self.link('rivet:furnace') + '.', '',
                 '## Crafting stations', '', '| Station | Grid or process |', '|---|---|', '| Personal crafting | 2×2 in your inventory |']
        for item_id, text in [('rivet:workbench', '3×3'), ('rivet:machinist_bench', '4×4'), ('rivet:furnace', 'Fuel-driven smelting and cooking'), ('rivet:crusher', 'Powered ore processing')]:
            lines += [f'| {self.icon(item_id, 48, True)} | {text} |']
        lines += ['', '## How to read a recipe', '',
                  '- **Shaped:** match the icon positions. Blank cells stay empty. Patterns may move inside a compatible grid; horizontal mirroring is allowed only where the recipe says so.',
                  '- **Shapeless:** positions do not matter. Numbers show the quantity needed in each occupied slot; industrial recipes can require several items in one slot.',
                  '- **Ingredients:** the table below each grid totals the cost of one operation. The output count is per operation, not per ingredient.',
                  '- **Stations:** a larger crafting grid can make smaller-grid recipes. Furnaces and crushers process items separately from grid crafting.', '',
                  'In the game’s item sidebar, left-click an item for recipes and right-click for uses. **Ctrl-click the recipe output** to place its ingredients from your inventory into a compatible open crafting grid; click the resulting crafting output to craft.', '',
                  '## Browse recipes by station', '', 'Choose a result below to open its item page at the exact recipe.', '']
        headings = [('', 'Personal crafting — 2×2'), ('rivet:workbench', 'Workbench — 3×3'), ('rivet:machinist_bench', "Machinist’s Bench — 4×4"), ('rivet:furnace', 'Furnace processing'), ('rivet:crusher', 'Crusher processing')]
        for station, heading in headings:
            recipes = [r for r in self.catalog['recipes'] if r['station'] == station]
            lines += ['## ' + heading, ''] + self.recipe_links(recipes)
        lines += ['## Workshop guides', '', '[Tanks](Tanks.md) · [Pumps and water](Pumps-and-water.md) · [Electricity and batteries](Electricity-and-batteries.md) · [Blue Signal](Blue-Signal.md)', '']
        counts = Counter('grid' if r['grid'] else r['station'] for r in self.catalog['recipes'])
        return '\n'.join(lines).replace('**91 grid recipes, 11 furnace recipes and 3 crusher recipes**',
               f'**{counts["grid"]} grid recipes, {counts["rivet:furnace"]} furnace recipes and {counts["rivet:crusher"]} crusher recipes**')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    reference = Reference(load_catalog())
    pages = {page(i): reference.item_page(i) for i in reference.items}
    pages.update({'Items.md': reference.index(), 'Crafting-Recipes.md': reference.crafting()})
    stale = [name for name, content in pages.items() if not (WIKI / name).is_file() or (WIKI / name).read_text() != content]
    obsolete = [p for p in WIKI.glob('Item-*.md') if p.name not in pages and p.read_text().startswith(MARKER)]
    if args.check:
        if stale or obsolete:
            raise SystemExit('Generated pages need refreshing: ' + ', '.join(stale + [p.name for p in obsolete]))
    else:
        for name, content in pages.items():
            (WIKI / name).write_text(content, encoding='utf-8')
        for path in obsolete:
            path.unlink()
    print(f'{"Checked" if args.check else "Generated"} {len(reference.items)} item pages and 2 indexes; {len(reference.catalog["recipes"])} recipes.')


if __name__ == '__main__':
    main()
